# Generated by Django 6.1 on 2026-08-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seed_disciplines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for opponent'), ('selecting', 'Selecting disciplines'), ('active', 'Active'), ('finished', 'Finished')], default='waiting', max_length=20),
        ),
    ]
